### ISSUE TITLE
Webdriver exception at find_element_by_id method

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.behavior.featuredimage#36] opened 2016-12-06 17:56 UTC
At one customer this exception is raised:

```python
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 105, in __call__
  Module Products.CMFFormController.Script, line 145, in __call__
  Module Products.CMFCore.FSPythonScript, line 127, in __call__
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 344, in _exec
  Module script, line 47, in content_status_modify
   - <FSControllerPythonScript at /Plone/pitacos/se-gritar-pega-ladrao-1/content_status_modify>
   - Line 47
  Module Products.CMFCore.WorkflowTool, line 241, in doActionFor
  Module Products.CMFCore.WorkflowTool, line 570, in _invokeWithNotification
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module collective.behavior.featuredimage.subscriber, line 45, in update_featuredimage
  Module collective.behavior.featuredimage.subscriber, line 18, in _get_screenshot
  Module selenium.webdriver.remote.webdriver, line 269, in find_element_by_id
  Module selenium.webdriver.remote.webdriver, line 745, in find_element
  Module selenium.webdriver.remote.webdriver, line 236, in execute
  Module selenium.webdriver.remote.errorhandler, line 194, in check_response
NoSuchElementException: Message: {"errorMessage":"Unable to find element with id 'featuredimage'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"94","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:52797","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"id\", \"sessionId\": \"d59a70d0-bbd7-11e6-a016-37225ccd7a44\", \"value\": \"featuredimage\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/d59a70d0-bbd7-11e6-a016-37225ccd7a44/element"}}
Screenshot: available via screen
```

The strange part is that the image is generated without problems.

It looks like we need to wait for the page or phantomjs be ready to select the element, here are some sources about the same issue:

* http://stackoverflow.com/questions/27599633/getting-error-in-click-method-of-selenium-in-python-when-i-find-the-element-fro
* http://stackoverflow.com/questions/30344223/exception-on-execution-phantomjs-selenium-webdriver-python-program
* http://selenium-python.readthedocs.io/waits.html

**Comment by hvelarde** [comment] 2017-01-26 13:59
I closed this by mistake, but I don't see any indicator of this isse in the log.

**Comment by hvelarde** [comment] 2017-01-27 13:40
the problem is a different one, I'll open a new issue.

**Closed as completed by hvelarde** 2017-01-27 13:40 UTC
